# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build RazorDemo/RazorDemo.csproj --configuration $(buildConfiguration)
- script: dotnet build RazorDemoTest/RazorDemoTest.csproj --configuration $(buildConfiguration)
- script: dotnet test *Test/*.csproj
  displayName: 'dotnet build $(buildConfiguration) and run unit test'
